<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLAUTHGenDate is an internal mark
   $CLAUTHGenDate = "1580172241";

/* claro_authUsernameCaseSensitive : Choose "No" if you use microsoft active directory (by default this authentication system is case-insensitive) */
$GLOBALS['claro_authUsernameCaseSensitive'] = TRUE;


/* claro_displayLocalAuthForm : If you are not using the local Claroline password to identify a user, disable this option so the access authentication form will not be available */
$GLOBALS['claro_displayLocalAuthForm'] = TRUE;


/* claro_secureLogin : You also need to configure your web server to allow SSL connections to the auth/login.php script ! */
$GLOBALS['claro_secureLogin'] = FALSE;


/* claro_displayLostPasswordLink : Disable this option if you are not using the local Claroline password to identify a user */
$GLOBALS['claro_displayLostPasswordLink'] = TRUE;


/* claro_loadDeprecatedPearAuthDriver : Choose "No" if you don't use any deprecated external auth driver. (If you are using the old PEAR-based LDAP authentication, you should replace it with the new ldap.conf.php driver found in inc/conf/extauth and set this option to "No" afterwards). */
$GLOBALS['claro_loadDeprecatedPearAuthDriver'] = TRUE;


/* claro_authDriversAutoDiscovery : Choose "No" if you don't use any external authentication drivers or if you prefer to set the list of authentication drivers to load in platform/extauth/drivers.list (one config file name by line). */
$GLOBALS['claro_authDriversAutoDiscovery'] = TRUE;



?>