<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLSSOGenDate is an internal mark
   $CLSSOGenDate = "1580172241";

/* ssoEnabled : If false, other fields are optional */
$GLOBALS['ssoEnabled'] = FALSE;


/* ssoCookieName : The name of the cookie. By default the name is "clarolineSsoCookie" */
$GLOBALS['ssoCookieName'] = 'clarolineSsoCookie';


/* ssoCookiePeriodValidity : Number of seconds before the cookie expires */
$GLOBALS['ssoCookiePeriodValidity'] = 3600;


/* ssoCookieDomain : The domain that the cookie is available.  To make the cookie available on all subdomains of example.com, you'd set it to ".example.com". The . is not required but makes it compatible with more browsers. Setting it to www.example.com  will make the cookie only available in the www  subdomain. */
$GLOBALS['ssoCookieDomain'] = 'www.my.domain.com';


/* ssoCookiePath : The path on the server in which the cookie will be available on.  If set to "/", the cookie will be available within the entire domain. If set to "/foo/", the cookie will only be available within the /foo/ directory and all sub-directories such as /foo/bar/ of domain. The default value is the current directory that the cookie is being set in. */
$GLOBALS['ssoCookiePath'] = '/';


/* ssoAuthenticationKeyList : A list of keys allowing requests to the Claroline SSO server. The SSO client has to provide one of the keys contained into this list to receive any answer from the Claroline SSO server. */
$GLOBALS['ssoAuthenticationKeyList'] = 'array()';



?>