<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLCHATGenDate is an internal mark
   $CLCHATGenDate = "1580172245";

/* msg_list_refresh_rate : Time to automatically refresh the list of messages in user's view. Each refresh is a request to your server.Too low value can be hard for your server. Too high value can be hard for user. */
$GLOBALS['msg_list_refresh_rate'] = 10;


/* user_list_refresh_rate : Time to automatically refresh the users list in user's view. Each refresh is a request to your server.Too low value can be hard for your server. Too high value can be hard for user. */
$GLOBALS['user_list_refresh_rate'] = 20;


/* max_nick_length : If the name and the firstname are longer than this value, the script reduce it.For revelance, it's interesting to not work with to little value */
$GLOBALS['max_nick_length'] = 20;



?>