<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDOCGenDate is an internal mark
   $CLDOCGenDate = "1580172244";

/* maxFilledSpace_for_course : Disk space allowed to each course */
$GLOBALS['maxFilledSpace_for_course'] = 100000000;


/* maxFilledSpace_for_groups : Disk space allowed to each group */
$GLOBALS['maxFilledSpace_for_groups'] = 1000000;


/* thumbnailWidth : Thumbnail width */
$GLOBALS['thumbnailWidth'] = 75;


/* numberOfRows : Number of rows displayed per page */
$GLOBALS['numberOfRows'] = 3;


/* numberOfCols : Number of columns displayed per page */
$GLOBALS['numberOfCols'] = 4;


/* openNewWindowForDoc : When users click on a document, it opens a new window */
$GLOBALS['openNewWindowForDoc'] = FALSE;


/* cldoc_allowAnonymousToDownloadFolder : This option can be used to prevent web crawlers to download an archive of the folder */
$GLOBALS['cldoc_allowAnonymousToDownloadFolder'] = TRUE;


/* cldoc_allowNonManagersToDownloadFolder : This option can be used to prevent users which do not have manager rights in documents to download an archive of the folder */
$GLOBALS['cldoc_allowNonManagersToDownloadFolder'] = TRUE;


/* cldoc_customTmpPath : Leave empty to use the default one (which is courses/<COURSEID>/tmp/zip) */
/*
Path to the temporary zip folder
*/
$GLOBALS['cldoc_customTmpPath'] = '';


/* cldoc_notifyAllFilesWhenUncompressingArchives : If set to true, the creation of every individual file contained in an archive will be notified (i.e. added to the new items for the course). If set to false (default) only the modification of the folder in which the archived is uncompressed will be notified. */
$GLOBALS['cldoc_notifyAllFilesWhenUncompressingArchives'] = FALSE;



?>