<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDSCGenDate is an internal mark
   $CLDSCGenDate = "1580172244";

/* cldsc_use_new_ordering_of_labels : Display description elements corresponding to others at the end */
$GLOBALS['cldsc_use_new_ordering_of_labels'] = FALSE;



?>