<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLHOMEGenDate is an internal mark
   $CLHOMEGenDate = "1580172241";

/* course_order_by : Order course by */
$GLOBALS['course_order_by'] = 'official_code';


/* categories_order_by : Order categories by */
$GLOBALS['categories_order_by'] = 'rank';


/* course_categories_hidden_to_anonymous : Hide course categories to anonymous */
$GLOBALS['course_categories_hidden_to_anonymous'] = FALSE;


/* userCourseListGroupByCategories : Group user courses by categories */
$GLOBALS['userCourseListGroupByCategories'] = FALSE;


/* display_former_homepage : Display former Claroline's home page instead of user's desktop */
$GLOBALS['display_former_homepage'] = FALSE;


/* userDesktopMessageCollapsedByDefault : Hide textzone on user desktop by default */
$GLOBALS['userDesktopMessageCollapsedByDefault'] = TRUE;



?>