<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLKCACHEGenDate is an internal mark
   $CLKCACHEGenDate = "1580172241";

/* cache_lifeTime : Time to keep a cache as valid */
$GLOBALS['cache_lifeTime'] = 10;


/* cache_automaticCleaningFactor : write n-1 times without check if (others) cached files are or not deprecated */
$GLOBALS['cache_automaticCleaningFactor'] = 40;



?>