<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLUSRGenDate is an internal mark
   $CLUSRGenDate = "1580172245";

/* linkToUserInfo : Allow users to see detailed informations about other users */
$GLOBALS['linkToUserInfo'] = TRUE;


/* user_email_hidden_to_anonymous : Don't display email of the users to anonymous (to avoid spam) */
$GLOBALS['user_email_hidden_to_anonymous'] = FALSE;


/* nbUsersPerPage : Number of user per page */
$GLOBALS['nbUsersPerPage'] = 25;


/* is_coursemanager_allowed_to_register_single_user : Teachers can register new users to the campus */
$GLOBALS['is_coursemanager_allowed_to_register_single_user'] = TRUE;


/* is_coursemanager_allowed_to_enroll_single_user : Teacher can add a user in his course */
$GLOBALS['is_coursemanager_allowed_to_enroll_single_user'] = TRUE;


/* is_coursemanager_allowed_to_import_user_list : Teacher can import user list in his course */
$GLOBALS['is_coursemanager_allowed_to_import_user_list'] = TRUE;


/* is_coursemanager_allowed_to_import_user_class : Teachers are allowed to register whole classes to their courses */
$GLOBALS['is_coursemanager_allowed_to_import_user_class'] = TRUE;


/* is_coursemanager_allowed_to_export_user_list : Teacher can export user list from his course */
$GLOBALS['is_coursemanager_allowed_to_export_user_list'] = TRUE;


/* export_sensitive_data_for_admin : Platform admin can export username, user_id and password */
$GLOBALS['export_sensitive_data_for_admin'] = FALSE;


/* export_user_username : Teacher can export username */
$GLOBALS['export_user_username'] = FALSE;


/* export_user_id : Teacher can export user id */
$GLOBALS['export_user_id'] = FALSE;


/* export_user_password : Teacher can export password */
$GLOBALS['export_user_password'] = FALSE;


/* export_user_password_encrypted : Encrypt exported password using md5 algorithm for teacher */
$GLOBALS['export_user_password_encrypted'] = TRUE;


/* update_user_properties : Update properties of users on CVS import */
$GLOBALS['update_user_properties'] = FALSE;



?>