<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLWIKIGenDate is an internal mark
   $CLWIKIGenDate = "1580172245";

/* showWikiEditorToolbar : Show wiki syntax toolbar */
$GLOBALS['showWikiEditorToolbar'] = TRUE;


/* forcePreviewBeforeSaving : Force text preview before saving it */
$GLOBALS['forcePreviewBeforeSaving'] = FALSE;



?>