<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLWRKGenDate is an internal mark
   $CLWRKGenDate = "1580172244";

/* confval_def_sub_vis_change_only_new : Sets how the assignment property "default works visibility" acts.  It will change the visibility of all the new submissions or it will change the visibility of all submissions already done in the assignment and the new one.  */
$GLOBALS['confval_def_sub_vis_change_only_new'] = TRUE;


/* open_submitted_file_in_new_window : When users click on a submitted file, it opens a new window */
$GLOBALS['open_submitted_file_in_new_window'] = FALSE;


/* show_only_author : Sets if user can see only his own submissions (or those from his groups) or if he can see every visible submission. */
$GLOBALS['show_only_author'] = FALSE;


/* mail_notification : If activated, allows to define a notification policy for assignment submissions and feedbacks. */
$GLOBALS['mail_notification'] = FALSE;


/* automatic_mail_notification : Are notification emails sent automatically or on demand (configurable in the assignement tool). */
$GLOBALS['automatic_mail_notification'] = FALSE;


/* assignmentsPerPage : For assignments list */
$GLOBALS['assignmentsPerPage'] = 20;


/* usersPerPage : For submissions list */
$GLOBALS['usersPerPage'] = 20;


/* allow_download_all_submissions : Add a "Download all submissions" link in the teacher commands */
$GLOBALS['allow_download_all_submissions'] = FALSE;


/* max_file_size_per_works : Maximum size of a document that a user can upload */
$GLOBALS['max_file_size_per_works'] = 3000000;


/* allow_work_event_generation : Automatically insert an event in the calendar at the submission date */
$GLOBALS['allow_work_event_generation'] = TRUE;


/* clwrk_endDateDelay : Number of days by default between the start date and the end date of an assignment. */
$GLOBALS['clwrk_endDateDelay'] = 365;


/* clwrk_customTmpPath : Used when downloading the assignements. Leave empty to use the default one (which is located in courses/<COURSEID>/work/) */
/*
Path to the temporary zip folder
*/
$GLOBALS['clwrk_customTmpPath'] = '';



?>