<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 12:44 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLPROFILGenDate is an internal mark
   $CLPROFILGenDate = "1580172241";

/* show_agreement_panel : The content of this panel is editable in administration  */
$GLOBALS['show_agreement_panel'] = FALSE;


/* userOfficialCodeCanBeEmpty : Official code is */
$GLOBALS['userOfficialCodeCanBeEmpty'] = TRUE;


/* userMailCanBeEmpty : Accept email as valid (best choice) */
$GLOBALS['userMailCanBeEmpty'] = TRUE;


/* ask_for_official_code : Display the field official code in form */
$GLOBALS['ask_for_official_code'] = TRUE;


/* profile_editable : Which parts of the profile can be changed? */
$GLOBALS['profile_editable'] = array('name','official_code','login','password','email','phone','language','picture','skype');


/* allow_profile_picture : Allow user to add a picture to their profile */
$GLOBALS['allow_profile_picture'] = TRUE;


/* SECURE_PASSWORD_REQUIRED : Check if the password is not too easy to find */
if (!defined("SECURE_PASSWORD_REQUIRED")) define("SECURE_PASSWORD_REQUIRED",FALSE);


/* can_request_course_creator_status : This option insert a command in the user profile form to request a status of course creator. This request is sent by e-mail to platform administrator. */
$GLOBALS['can_request_course_creator_status'] = FALSE;


/* can_request_revoquation : This option insert a command in the user profile form to request the removal of the user from the platform.  This request is sent by e-mail to platform administrator.This option allow only to request it, and don't prework the answer */
$GLOBALS['can_request_revoquation'] = FALSE;


/* allowSelfRegProf : Are users allowed to create themselves a Course Creator account ? */
$GLOBALS['allowSelfRegProf'] = TRUE;



?>