version: "3"

services:
  webserver:
    image: test
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
    links: 
      - mysql
    volumes: 
     - ./www/html:/var/www/html
  mysql:
    build: ./mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - ./data/mysql}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root